# Generated by Django 5.1.1 on 2024-09-30 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='description',
        ),
        migrations.RemoveField(
            model_name='book',
            name='published_date',
        ),
        migrations.AddField(
            model_name='author',
            name='about',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='author',
            name='fans_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='image_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='ratings_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='text_reviews_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='author',
            name='works_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='book_id',
            field=models.CharField(default='default_book_id', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='book',
            name='work_id',
            field=models.CharField(default='default_book_id', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
